FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-runtime

WORKDIR /workspace
COPY . /workspace

RUN conda install torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
RUN conda install cctbx202211::rdkit

RUN conda install pyg  pyyaml  biopython -c pyg
RUN pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.0.0+cu117.html
RUN pip install e3nn fair-esm spyrmsd

RUN conda install -c conda-forge openmm
RUN conda install -c conda-forge pdbfixer
RUN conda install -c conda-forge libstdcxx-ng
RUN conda install -c conda-forge biopython
RUN conda install -c conda-forge compilers
RUN conda install conda_packages/ambertools-22.5.conda
RUN conda install conda_packages/openmmforcefields-0.12.0.conda
RUN conda install conda_packages/openff-toolkit-0.15.2.conda

ENTRYPOINT ["python", "main.py"]